### ISSUE TITLE
Whitelist IP address for gateways to prevent DOS

### ISSUE THREAD

**Issue by gregbugaj** [marieai/marie-ai#50]
Need to implement custom middleware for the gateways to allow connections from whitelisted IP only.

Formats:
```
172.16.10.0/24
172.16.10.128
```

**Comment by scstauf** [comment]
Added WhitelistMiddleware for whitelisting ip addresses. Use the ip_whitelist_path parameter on HTTPGateway to specify a file containing CRLF delimited strings of CIDR compliant IP addresses. This list will be used by the WhitelistMiddleware to filter out requests from IP addresses not in the whitelist. If a request is received by an address not in the whitelist, a warning log entry will be written saying "Non-whitelist request from host {request.client.host}" and an HTTPException with an HTTP_403_FORBIDDEN status will be raised.
