### ISSUE TITLE
Not found the DiT model

### ISSUE THREAD

**Issue by ocrifydotnet** [marieai/marie-ai#75]
Checkpoint ../../model_zoo/unilm/dit/text_detection/td-syn_dit-b_mrcnn.pth not found!

**Comment by gregbugaj** [comment]
You have to download the models your self as they are pretty large. 

# DiT for Text Detection

https://github.com/microsoft/unilm/tree/master/dit/text_detection


# initialized checkpoint

DiT-base-syn 	dit_base_patch16_224_syn
https://layoutlm.blob.core.windows.net/dit/dit-fts/td-syn_dit-b_mrcnn.pth

DiT-large-syn 	dit_large_patch16_224_syn 

https://layoutlm.blob.core.windows.net/dit/dit-fts/td-syn_dit-l_mrcnn.pth

**Comment by AhmadHakami** [comment]
please update the weights links

thanks in advance :)

**Comment by Rithsek99** [comment]
Ref: 
https://github.com/microsoft/unilm/blob/master/dit/README.md?plain=1#L25

# initialized checkpoint

DiT-base-syn 	dit_base_patch16_224_syn
https://layoutlm.blob.core.windows.net/dit/dit-fts/td-syn_dit-b_mrcnn.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D

DiT-large-syn 	dit_large_patch16_224_syn 

https://layoutlm.blob.core.windows.net/dit/dit-fts/td-syn_dit-l_mrcnn.pth?sv=2022-11-02&ss=b&srt=o&sp=r&se=2033-06-08T16:48:15Z&st=2023-06-08T08:48:15Z&spr=https&sig=a9VXrihTzbWyVfaIDlIT1Z0FoR1073VB0RLQUMuudD4%3D
